apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-management-api
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: user-management-api
      labels:
        app: user-management-api
    spec:
      containers:
      - image: mirna/user-management-api:1
        name: user-management-api
---
apiVersion: v1
kind: Service
metadata:
  name: user-management-api
spec:
  type: ClusterIP
  ports:
  - port: 8081
  selector:
    app: user-management-api 
